scanty:
  title: a scanty microblog
  author: John Doe
  url_base: http://localhost:4567/
  admin_password: change me
  admin_cookie_key: scanty_admin
  admin_cookie_value: 51d6d976913ace58
  disqus_shortname:

jabbit:
  login: jabbit@your-jabber-provider.com
  password: change me